---
version: '3'

services:
  phpipam-mysql:
    image: mysql:5.7
    container_name: phpipam-mysql
    restart: unless-stopped
    volumes:
      - /var/docker/data/phpipam/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Tringa08 # Starkes Passwort setzen!

  phpipam-phpipam:
    image: pierrecdn/phpipam:latest
    container_name: phpipam-phpipam
    restart: unless-stopped
    environment:
      - MYSQL_ENV_MYSQL_USER=root
      - MYSQL_ENV_MYSQL_ROOT_PASSWORD=Tringa08 # Starkes Passwort setzen!
      - MYSQL_ENV_MYSQL_HOST=phpipam-mysql
    depends_on:
      - phpipam-mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.phpipam-https.redirectscheme.scheme=https"
      - "traefik.http.routers.phpipam-http.entrypoints=web"
      - "traefik.http.routers.phpipam-http.rule=Host(`phpipam.dardania.dev`)" #Domain anpassen
      - "traefik.http.routers.phpipam-http.middlewares=phpipam-https@docker"
      - "traefik.http.routers.phpipam.entrypoints=web-secure"
      - "traefik.http.routers.phpipam.rule=Host(`phpipam.dardania.dev`)" #Domain anpassen
      - "traefik.http.routers.phpipam.tls=true"
      - "traefik.http.routers.phpipam.tls.certresolver=default"
      - "traefik.http.routers.phpipam.middlewares=secHeaders@file"
      - "traefik.http.services.phpipam.loadbalancer.server.port=80"
    networks:
      - traefik_proxy
      - default
    
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
